### ISSUE TITLE
audit-logging plugin 2.0.0-SNAPSHOT runtime error

### ISSUE THREAD

**Issue by csusu** [robertoschwald/grails-audit-logging-plugin#107]
After I upgraded my project from grails 2.4.2 to grails 3.0.8 and use the **audit-logging plugin 2.0.0-SNAPSHOT**,when I am running my project it complains an error:
>ERROR grails.plugins.orm.auditable.AuditLogListener - Audit plugin unable to process update event for WorkEvent
groovy.lang.MissingMethodException: No signature of method: grails.plugins.orm.auditable.AuditLogListener$_replaceByReplacementPatterns_closure12.doCall() is applicable for argument types: (java.lang.String, org.grails.config.NavigableMap) values: [local, [example:[xyz:]]]
Possible solutions: doCall(java.lang.String, java.lang.String), findAll(), findAll()
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:286) [groovy-2.4.4.jar:2.4.4]
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1019) [groovy-2.4.4.jar:2.4.4]
        at groovy.lang.Closure.call(Closure.java:426) [groovy-2.4.4.jar:2.4.4]
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.callClosureForMapEntry(DefaultGroovyMethods.java:5226) ~[groovy-2.4.4.jar:2.4.4]
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2107) ~[groovy-2.4.4.jar:2.4.4]
        at org.codehaus.groovy.runtime.dgm$163.invoke(Unknown Source) ~[groovy-2.4.4.jar:2.4.4]
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoMetaMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:251) ~[groovy-2.4.4.jar:2.4.4]
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.call(PogoMetaMethodSite.java:71) [groovy-2.4.4.jar:2.4.4]
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48) [groovy-2.4.4.jar:2.4.4]
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113) [groovy-2.4.4.jar:2.4.4]
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125) [groovy-2.4.4.jar:2.4.4]
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callSafe(AbstractCallSite.java:87) [groovy-2.4.4.jar:2.4.4]

So,how can I resolve this error?

**Comment by robertoschwald** [comment]
Looking into it.

**Comment by robertoschwald** [comment]
Could you please use 2.0.0 Release?
