### ISSUE TITLE
Configuration confusion in 2.0.0 with Grails 3.0

### ISSUE THREAD

**Issue by squarepegsys** [robertoschwald/grails-audit-logging-plugin#115]
I'm converting a Grails 2 app to Grails 3.0.10. I looked that documentation here to make sure I have it configured correctly:
https://robertoschwald.github.io/grails-audit-logging-plugin/latest/guide/usage.html#configuration

My closure is pretty straightforward:

     auditLog {
         logIds = true
         actorClosure = { request, session ->
        if (request.applicationContext.springSecurityService.principal instanceof String){
            return request.applicationContext.springSecurityService.principal
        }
        def username = request.applicationContext.springSecurityService.principal?.username

        if (!username) {
            username = 'system'
        }

        if (SpringSecurityUtils.isSwitched()){
            username = SpringSecurityUtils.switchedUserOriginalUsername+" AS "+username
        }

        return username
    }
     }

If I use that, I get :

    ERROR g.plugins.orm.auditable.ReflectionUtils  : Your auditLog configuration settings use 
    the old prefix  'auditLog' but must now use 'grails.plugin.auditLog'

If I change `auditLog` to `grails.plugin.auditLog` I get a long stacktrace that ends with:

    Caused by: groovy.lang.MissingMethodException: No signature of method:     groovy.util.ConfigObject.auditLog() is applicable for argument types: (script14519274704937623851$_run_closure3) values: [script14519274704937623851$_run_closure3@7c079ab0]
        at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:58)
        at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:54)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)

Seems that something is still wrong with the configuration.

**Comment by robertoschwald** [comment]
it works when using config closures as you've written on Slack. Closing issue.

**Comment by tcraib** [comment]
@robertoschwald I have run into the same issues as stated here while upgrading from grails 2.x.x to 3.x.x.
Could you please provide the config closures you supplied on Slack here?

**Comment by robertoschwald** [comment]
https://github.com/robertoschwald/grails-audit-logging-plugin/blob/master/examples/audit-test/grails-app/conf/application.groovy

**Comment by tcraib** [comment]
Thank you. All sorted

**Comment by robertoschwald** [comment]
Btw: Its documented also:  https://robertoschwald.github.io/grails-audit-logging-plugin/latest/plugin.html#example-configuration
