### ISSUE TITLE
TRUNCATE_LENGTH - not supported?

### ISSUE THREAD

**Issue by jglapa** [robertoschwald/grails-audit-logging-plugin#142]
Hi, is the `TRUNCATE_LENGTH` config property still supported in `v2` of the plugin? I'm getting ConstraintViolationExceptions when the `old|newValue` are longer than my column limit - I've set the TRUNCATE_LENGTH to less than that.
I've skimmed through the src and couldn't find any references to that property anywhere in the code?

**Comment by robertoschwald** [comment]
Thanks for mentioning. We removed it in 9c1e675fd2b7c05323d4907b064cb3b37c2baaf9

We thought its a feature no one uses, but that seems to be not correct. Will re-introduce soon.

**Comment by jglapa** [comment]
any predictions for releasing this?

**Comment by robertoschwald** [comment]
Not yet. Pretty busy currently.

**Comment by robertoschwald** [comment]
@jglapa Please try 2.0.6-SNAPSHOT.  

Compared to the 1.x version, this one should be save if you define the TRUNCATE_LENGTH larger than your AuditTrail newValue maxSize constraint. It falls back to the size of the field. Please try it out.

Feedback appreciated.

**Comment by jglapa** [comment]
Looks as if it's doing the job. Thanks @robertoschwald

**Comment by robertoschwald** [comment]
Not completely. 
There is a bug - which I turn into a feature. TRUNCATE_LENGTH is not taken into account, but "truncateLength". Will log a warn in the future when TRUNCATE_LENGTH is defined. 

New 2.0.6-SNAPSHOT should be available in a few minutes.

Please change the param in your config then.

**Comment by jglapa** [comment]
ok, will do!

**Comment by robertoschwald** [comment]
2.0.6-SNAPSHOT is updated. Please test.

**Comment by jglapa** [comment]
having problems testing this right now due to
```
groovy.lang.MissingMethodException: No signature of method: java.lang.Integer.isEmpty() is applicable for argument types: () values: []
Possible solutions: identity(groovy.lang.Closure), dump(), inspect()
        at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:58)
        at org.codehaus.groovy.runtime.callsite.PojoMetaClassSite.call(PojoMetaClassSite.java:49)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:117)
        at grails.plugins.orm.auditable.AuditLoggingGrailsPlugin.determineTruncateLength(AuditLoggingGrailsPlugin.groovy:144)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
....
```

I suspect that the new snapshot is not _visible_ ? 
I've cleared gradle cache and it still downloads the following
```Download https://repo.grails.org/grails/core/org/grails/plugins/audit-logging/2.0.6-SNAPSHOT/audit-logging-2.0.6-20170606.173911-6.jar```

**Comment by robertoschwald** [comment]
In the repo, latest one is https://repo.grails.org/grails/core/org/grails/plugins/audit-logging/2.0.6-SNAPSHOT/audit-logging-2.0.6-20170607.133858-14.jar

**Comment by robertoschwald** [comment]
Maybe you should force your project to download SNAPSHOTS all the time. 

```
configurations.all {
    resolutionStrategy.cacheChangingModulesFor 0, 'seconds'
}
```

**Comment by jglapa** [comment]
works! 
thanks!

**Comment by robertoschwald** [comment]
see release 2.0.6
