### ISSUE TITLE
GPAUDITLOGGING-34: org.hibernate.cache.NoCachingEnabledException when using with mySql

### ISSUE THREAD

**Issue by robertoschwald** [robertoschwald/grails-audit-logging-plugin#68]
Original Reporter: martinstephenson
Environment: WIndows 7, SpringSource 2.7.1, Grails 1.3.7, mySQL 5.5.8
Version: Grails-AuditLogging 0.5.4
Migrated From: http://jira.grails.org/browse/GPAUDITLOGGING-34

I am trying to use the Audit Loggin plugin but cannot get it to run with mySql - If I switch back to the default hsqldb in DataSource.groovy I do not get the error

Error is :
==========
Welcome to Grails 1.3.7 - http://grails.org/
Licensed under Apache Standard License 2.0
Grails home is set to: C:\Program Files\springsource\grails-1.3.7\

Base Directory: C:\Development\Springsource\AuditLogTest
Resolving dependencies...
Dependencies resolved in 1042ms.
Running script C:\Program Files\springsource\grails-1.3.7\scripts\RunApp.groovy
Environment set to development
  [groovyc] Compiling 2 source files to C:\Development\Springsource\AuditLogTest\target\classes
   [delete] Deleting directory C:\Users\Martin Stephenson\.grails\1.3.7\projects\AuditLogTest\tomcat
Running Grails application..
2011-09-12 20:05:47,405 [main] ERROR context.GrailsContextLoader  - Error executing bootstraps: Error creating bean with name 'messageSource': Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'transactionManager': Cannot resolve reference to bean 'sessionFactory' while setting bean property 'sessionFactory'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sessionFactory': Invocation of init method failed; nested exception is org.hibernate.cache.NoCachingEnabledException: Second-level cache is not enabled for usage [hibernate.cache.use_second_level_cache | hibernate.cache.use_query_cache]
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'messageSource': Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'transactionManager': Cannot resolve reference to bean 'sessionFactory' while setting bean property 'sessionFactory'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sessionFactory': Invocation of init method failed; nested exception is org.hibernate.cache.NoCachingEnabledException: Second-level cache is not enabled for usage [hibernate.cache.use_second_level_cache | hibernate.cache.use_query_cache]
	at org.grails.tomcat.TomcatServer.start(TomcatServer.groovy:212)
	at grails.web.container.EmbeddableServer$start.call(Unknown Source)
	at _GrailsRun_groovy$_run_closure5_closure12.doCall(_GrailsRun_groovy:158)
	at _GrailsRun_groovy$_run_closure5_closure12.doCall(_GrailsRun_groovy)
	at _GrailsSettings_groovy$_run_closure10.doCall(_GrailsSettings_groovy:280)
	at _GrailsSettings_groovy$_run_closure10.call(_GrailsSettings_groovy)
	at _GrailsRun_groovy$_run_closure5.doCall(_GrailsRun_groovy:149)
	at _GrailsRun_groovy$_run_closure5.call(_GrailsRun_groovy)
	at _GrailsRun_groovy.runInline(_GrailsRun_groovy:116)
	at _GrailsRun_groovy.this$4$runInline(_GrailsRun_groovy)
	at _GrailsRun_groovy$_run_closure1.doCall(_GrailsRun_groovy:59)
	at RunApp$_run_closure1.doCall(RunApp:33)
	at gant.Gant$_dispatch_closure5.doCall(Gant.groovy:381)
	at gant.Gant$_dispatch_closure7.doCall(Gant.groovy:415)
	at gant.Gant$_dispatch_closure7.doCall(Gant.groovy)
	at gant.Gant.withBuildListeners(Gant.groovy:427)
	at gant.Gant.this$2$withBuildListeners(Gant.groovy)
	at gant.Gant$this$2$withBuildListeners.callCurrent(Unknown Source)
	at gant.Gant.dispatch(Gant.groovy:415)
	at gant.Gant.this$2$dispatch(Gant.groovy)
	at gant.Gant.invokeMethod(Gant.groovy)
	at gant.Gant.executeTargets(Gant.groovy:590)
	at gant.Gant.executeTargets(Gant.groovy:589)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'transactionManager': Cannot resolve reference to bean 'sessionFactory' while setting bean property 'sessionFactory'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sessionFactory': Invocation of init method failed; nested exception is org.hibernate.cache.NoCachingEnabledException: Second-level cache is not enabled for usage [hibernate.cache.use_second_level_cache | hibernate.cache.use_query_cache]
	... 23 more
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sessionFactory': Invocation of init method failed; nested exception is org.hibernate.cache.NoCachingEnabledException: Second-level cache is not enabled for usage [hibernate.cache.use_second_level_cache | hibernate.cache.use_query_cache]
	... 23 more
Caused by: org.hibernate.cache.NoCachingEnabledException: Second-level cache is not enabled for usage [hibernate.cache.use_second_level_cache | hibernate.cache.use_query_cache]
	... 23 more

DataSource.groovy is :
======================

dataSource {
    pooled = true
    driverClassName = "com.mysql.jdbc.Driver"
    username = "root"
    password = ""

hibernate {
    cache.use_second_level_cache = true
    cache.use_query_cache = true
    cache.provider_class = 'net.sf.ehcache.hibernate.EhCacheProvider'
}
// environment specific settings
environments {
    development {
        dataSource {
            dbCreate = "update" // one of 'create', 'create-drop','update'
			url = "jdbc:mysql://127.0.0.1:3306/AUDIT_DEV"
        }
    }
    test {
        dataSource {
            dbCreate = "update"
			url = "jdbc:mysql://127.0.0.1:3306/AUDIT_TEST"
        }
    }
    production {
        dataSource {
            dbCreate = "update"
            url = "jdbc:mysql://127.0.0.1:3306/AUDIT_PROD"
        }
    }
}
}

**Comment by robertoschwald** [comment]
roos added a comment - 05/Apr/15 11:49 PM

Closing this, as its an individual plugin config problem. No reaction from issue author.
